#   server:
#   port: 因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003
server:
  port: 8002
spring:
  application:
    name: PRODUCT-DATA-SERVICE
    #springcloud链路追踪服务
    zipkin:
      base-url: http://localhost:9411
    #end
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
