package iot.oamsvc.dao;

import iot.oamsvc.entity.StaffOperationLog;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface StaffOperationLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_op_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer logId);

    int deleteByExact(StaffOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_op_log
     *
     * @mbg.generated
     */
    int insert(StaffOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_op_log
     *
     * @mbg.generated
     */
    StaffOperationLog selectByPrimaryKey(Integer logId);

    List<StaffOperationLog> selectByLike(StaffOperationLog record);

    List<StaffOperationLog> selectByExact(StaffOperationLog record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_op_log
     *
     * @mbg.generated
     */
    List<StaffOperationLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_op_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StaffOperationLog record);
    int updateByExact(StaffOperationLog record);
}