package iot.oamsvc.dao;

import iot.oamsvc.entity.SysAlarmLog;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface SysAlarmLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer alarmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_log
     *
     * @mbg.generated
     */
    int insert(SysAlarmLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_log
     *
     * @mbg.generated
     */
    SysAlarmLog selectByPrimaryKey(Integer alarmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_log
     *
     * @mbg.generated
     */
    List<SysAlarmLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysAlarmLog record);
}