##eureka:
#  #  client:
#  #    serviceUrl:
#  #      defaultZone: http://localhost:8762/eureka/
#  spring:
#    application:
#      name: product-view-service-feign
#      #springcloud链路服务追踪
#      zipkin:
#        base-url: http://localhost:9411
#      #end
#    thymeleaf:
#      cache: false
#      prefix: classpath:/templates/
#      suffix: .html
#      encoding: UTF-8
#      mode: HTML5
#      servlet:
#        content-type: text/html
spring:
  application:
    name:  product-view-service-feign
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  zipkin:
    base-url: http://localhost:9411