#eureka:
  #  client:
  #    serviceUrl:
  #      defaultZone: http://localhost:8762/eureka/
spring:
  application:
    name:  product-view-service-feign
#thymeleaf配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
#服务链路追踪
  zipkin:
    base-url: http://localhost:9411
#新增路径访问允许---》这样才能够访问/actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

#熔断器新增：
#开启熔断器
feign.hystrix.enabled: true
